import { type Position } from "@/components/games/engine/football-pitch"

export const FORMATIONS: Record<string, Position[]> = {
  "4-3-3": [
    { id: 0, label: "GK", row: 4.8, col: 2 },
    { id: 1, label: "LB", row: 3.6, col: 0 },
    { id: 2, label: "CB", row: 3.9, col: 1.3 },
    { id: 3, label: "CB", row: 3.9, col: 2.7 },
    { id: 4, label: "RB", row: 3.6, col: 4 },
    { id: 5, label: "CM", row: 2.2, col: 1.3 },
    { id: 6, label: "CM", row: 2.2, col: 2 },
    { id: 7, label: "CM", row: 2.2, col: 2.7 },
    { id: 8, label: "LW", row: 0.8, col: 0 },
    { id: 9, label: "ST", row: 0.4, col: 2 },
    { id: 10, label: "RW", row: 0.8, col: 4 },
  ],
  "4-3-3 (1)": [
    { id: 0, label: "GK", row: 4.8, col: 2 },
    { id: 1, label: "LB", row: 3.6, col: 0 },
    { id: 2, label: "CB", row: 3.9, col: 1.3 },
    { id: 3, label: "CB", row: 3.9, col: 2.7 },
    { id: 4, label: "RB", row: 3.6, col: 4 },
    { id: 5, label: "CM", row: 1.6, col: 1.3 },
    { id: 6, label: "CDM", row: 2.8, col: 2 },
    { id: 7, label: "CM", row: 1.6, col: 2.7 },
    { id: 8, label: "LW", row: 0.8, col: 0 },
    { id: 9, label: "ST", row: 0.4, col: 2 },
    { id: 10, label: "RW", row: 0.8, col: 4 },
  ],
  "4-3-3 (2)": [
    { id: 0, label: "GK", row: 4.8, col: 2 },
    { id: 1, label: "LB", row: 3.6, col: 0 },
    { id: 2, label: "CB", row: 3.9, col: 1.3 },
    { id: 3, label: "CB", row: 3.9, col: 2.7 },
    { id: 4, label: "RB", row: 3.6, col: 4 },
    { id: 5, label: "CM", row: 1.2, col: 1.3 },
    { id: 6, label: "CM", row: 1.2, col: 2.7 },
    { id: 7, label: "CDM", row: 2.4, col: 2 },
    { id: 8, label: "LW", row: 0.8, col: 0 },
    { id: 9, label: "ST", row: 0.4, col: 2 },
    { id: 10, label: "RW", row: 0.8, col: 4 },
  ],
  "4-3-3 (3)": [
    { id: 0, label: "GK", row: 4.8, col: 2 },
    { id: 1, label: "LB", row: 3.6, col: 0 },
    { id: 2, label: "CB", row: 3.9, col: 1.3 },
    { id: 3, label: "CB", row: 3.9, col: 2.7 },
    { id: 4, label: "RB", row: 3.6, col: 4 },
    { id: 5, label: "CDM", row: 2.6, col: 1.3 },
    { id: 6, label: "CM", row: 1.6, col: 2 },
    { id: 7, label: "CDM", row: 2.6, col: 2.7 },
    { id: 8, label: "LW", row: 0.8, col: 0 },
    { id: 9, label: "ST", row: 0.4, col: 2 },
    { id: 10, label: "RW", row: 0.8, col: 4 },
  ],
  "4-4-2": [
    { id: 0, label: "GK", row: 4.8, col: 2 },
    { id: 1, label: "LB", row: 3.6, col: 0 },
    { id: 2, label: "CB", row: 3.9, col: 1.3 },
    { id: 3, label: "CB", row: 3.9, col: 2.7 },
    { id: 4, label: "RB", row: 3.6, col: 4 },
    { id: 5, label: "LM", row: 2.2, col: 0 },
    { id: 6, label: "CM", row: 2.2, col: 1.3 },
    { id: 7, label: "CM", row: 2.2, col: 2.7 },
    { id: 8, label: "RM", row: 2.2, col: 4 },
    { id: 9, label: "ST", row: 0.5, col: 1.3 },
    { id: 10, label: "ST", row: 0.5, col: 2.7 },
  ],
  "4-4-2 (1)": [
    { id: 0, label: "GK", row: 4.8, col: 2 },
    { id: 1, label: "LB", row: 3.6, col: 0 },
    { id: 2, label: "CB", row: 3.9, col: 1.3 },
    { id: 3, label: "CB", row: 3.9, col: 2.7 },
    { id: 4, label: "RB", row: 3.6, col: 4 },
    { id: 5, label: "CM", row: 2.2, col: 1.3 },
    { id: 6, label: "CDM", row: 3.1, col: 2 },
    { id: 7, label: "CM", row: 2.2, col: 2.7 },
    { id: 8, label: "CAM", row: 1.3, col: 2 },
    { id: 9, label: "ST", row: 0.4, col: 1.3 },
    { id: 10, label: "ST", row: 0.4, col: 2.7 },
  ],
  "4-4-2 (2)": [
    { id: 0, label: "GK", row: 4.8, col: 2 },
    { id: 1, label: "LB", row: 3.6, col: 0 },
    { id: 2, label: "CB", row: 3.9, col: 1.3 },
    { id: 3, label: "CB", row: 3.9, col: 2.7 },
    { id: 4, label: "RB", row: 3.6, col: 4 },
    { id: 5, label: "LM", row: 2.2, col: 0 },
    { id: 6, label: "CDM", row: 3.1, col: 2 },
    { id: 7, label: "RM", row: 2.2, col: 4 },
    { id: 8, label: "CAM", row: 1.3, col: 2 },
    { id: 9, label: "ST", row: 0.4, col: 1.3 },
    { id: 10, label: "ST", row: 0.4, col: 2.7 },
  ],
  "3-5-2": [
    { id: 0, label: "GK", row: 4.8, col: 2 },
    { id: 1, label: "CB", row: 3.9, col: 0.8 },
    { id: 2, label: "CB", row: 3.9, col: 2 },
    { id: 3, label: "CB", row: 3.9, col: 3.2 },
    { id: 4, label: "LM", row: 2.2, col: 0 },
    { id: 5, label: "CDM", row: 3.1, col: 1.3 },
    { id: 6, label: "CAM", row: 1.3, col: 2 },
    { id: 7, label: "CDM", row: 3.1, col: 2.7 },
    { id: 8, label: "RM", row: 2.2, col: 4 },
    { id: 9, label: "ST", row: 0.4, col: 1.3 },
    { id: 10, label: "ST", row: 0.4, col: 2.7 },
  ],
  "3-4-3": [
    { id: 0, label: "GK", row: 4.8, col: 2 },
    { id: 1, label: "CB", row: 3.9, col: 0.8 },
    { id: 2, label: "CB", row: 3.9, col: 2 },
    { id: 3, label: "CB", row: 3.9, col: 3.2 },
    { id: 4, label: "LM", row: 2.2, col: 0 },
    { id: 5, label: "CM", row: 2.2, col: 1.3 },
    { id: 6, label: "CM", row: 2.2, col: 2.7 },
    { id: 7, label: "RM", row: 2.2, col: 4 },
    { id: 8, label: "LW", row: 0.8, col: 0 },
    { id: 9, label: "ST", row: 0.4, col: 2 },
    { id: 10, label: "RW", row: 0.8, col: 4 },
  ],
  "5-3-2": [
    { id: 0, label: "GK", row: 4.8, col: 2 },
    { id: 1, label: "LB", row: 3.6, col: 0 },
    { id: 2, label: "CB", row: 3.9, col: 1 },
    { id: 3, label: "CB", row: 3.9, col: 2 },
    { id: 4, label: "CB", row: 3.9, col: 3 },
    { id: 5, label: "RB", row: 3.6, col: 4 },
    { id: 6, label: "CM", row: 2.2, col: 1.3 },
    { id: 7, label: "CDM", row: 3.1, col: 2 },
    { id: 8, label: "CM", row: 2.2, col: 2.7 },
    { id: 9, label: "ST", row: 0.4, col: 1.3 },
    { id: 10, label: "ST", row: 0.4, col: 2.7 },
  ],
  "5-4-1": [
    { id: 0, label: "GK", row: 4.8, col: 2 },
    { id: 1, label: "LB", row: 3.6, col: 0 },
    { id: 2, label: "CB", row: 3.9, col: 1 },
    { id: 3, label: "CB", row: 3.9, col: 2 },
    { id: 4, label: "CB", row: 3.9, col: 3 },
    { id: 5, label: "RB", row: 3.6, col: 4 },
    { id: 6, label: "LM", row: 2.2, col: 0.2 },
    { id: 7, label: "CM", row: 2.2, col: 1.3 },
    { id: 8, label: "CM", row: 2.2, col: 2.7 },
    { id: 9, label: "RM", row: 2.2, col: 3.8 },
    { id: 10, label: "ST", row: 0.4, col: 2 },
  ],
  "4-2-4": [
    { id: 0, label: "GK", row: 4.8, col: 2 },
    { id: 1, label: "LB", row: 3.6, col: 0 },
    { id: 2, label: "CB", row: 3.9, col: 1.3 },
    { id: 3, label: "CB", row: 3.9, col: 2.7 },
    { id: 4, label: "RB", row: 3.6, col: 4 },
    { id: 5, label: "CM", row: 2.2, col: 1.5 },
    { id: 6, label: "CM", row: 2.2, col: 2.5 },
    { id: 7, label: "LW", row: 0.8, col: 0 },
    { id: 8, label: "ST", row: 0.4, col: 1.3 },
    { id: 9, label: "ST", row: 0.4, col: 2.7 },
    { id: 10, label: "RW", row: 0.8, col: 4 },
  ],
}
