import { type Position } from "@/components/football-pitch"

export const FORMATIONS: Record<string, Position[]> = {
  "4-3-3": [
    { id: 0, label: "GK", row: 4, col: 2 },
    { id: 1, label: "LB", row: 3, col: 0 },
    { id: 2, label: "CB", row: 3, col: 1.5 },
    { id: 3, label: "CB", row: 3, col: 2.5 },
    { id: 4, label: "RB", row: 3, col: 4 },
    { id: 5, label: "CM", row: 2, col: 0.5 },
    { id: 6, label: "CM", row: 2, col: 2 },
    { id: 7, label: "CM", row: 2, col: 3.5 },
    { id: 8, label: "LW", row: 1, col: 0.5 },
    { id: 9, label: "ST", row: 1, col: 2 },
    { id: 10, label: "RW", row: 1, col: 3.5 },
  ],
  "4-4-2": [
    { id: 0, label: "GK", row: 4, col: 2 },
    { id: 1, label: "LB", row: 3, col: 0 },
    { id: 2, label: "CB", row: 3, col: 1.5 },
    { id: 3, label: "CB", row: 3, col: 2.5 },
    { id: 4, label: "RB", row: 3, col: 4 },
    { id: 5, label: "LM", row: 2, col: 0 },
    { id: 6, label: "CM", row: 2, col: 1.5 },
    { id: 7, label: "CM", row: 2, col: 2.5 },
    { id: 8, label: "RM", row: 2, col: 4 },
    { id: 9, label: "ST", row: 1, col: 1.5 },
    { id: 10, label: "ST", row: 1, col: 2.5 },
  ],
  "3-5-2": [
    { id: 0, label: "GK", row: 4, col: 2 },
    { id: 1, label: "CB", row: 3, col: 1 },
    { id: 2, label: "CB", row: 3, col: 2 },
    { id: 3, label: "CB", row: 3, col: 3 },
    { id: 4, label: "LM", row: 2, col: 0 },
    { id: 5, label: "CM", row: 2, col: 1.3 },
    { id: 6, label: "CM", row: 2, col: 2 },
    { id: 7, label: "CM", row: 2, col: 2.7 },
    { id: 8, label: "RM", row: 2, col: 4 },
    { id: 9, label: "ST", row: 1, col: 1.5 },
    { id: 10, label: "ST", row: 1, col: 2.5 },
  ],
  "5-3-2": [
    { id: 0, label: "GK", row: 4, col: 2 },
    { id: 1, label: "LWB", row: 3, col: 0 },
    { id: 2, label: "CB", row: 3, col: 1 },
    { id: 3, label: "CB", row: 3, col: 2 },
    { id: 4, label: "CB", row: 3, col: 3 },
    { id: 5, label: "RWB", row: 3, col: 4 },
    { id: 6, label: "CM", row: 2, col: 1 },
    { id: 7, label: "CM", row: 2, col: 2 },
    { id: 8, label: "CM", row: 2, col: 3 },
    { id: 9, label: "ST", row: 1, col: 1.5 },
    { id: 10, label: "ST", row: 1, col: 2.5 },
  ],
}
